name: serene_backend
publish_to: 'none'
environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_web_socket: ^1.0.4

executables:
  server: server
