name:  Dart

on:
  push:
    branches: [ "main" ]
    paths:
      - "serene/**"
  pull_request:
    branches:  [ "main" ]
    paths:
      - "serene/**"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        working-directory: serene
        run: dart pub get

      - name:  Analyze project source
        working-directory: serene
        run: dart analyze

      - name: Run tests
        working-directory: serene
        run: dart test
