name:  Flutter

on:
  push: 
    branches: [ "main" ]
    paths:
      - "serene/**"
  pull_request:
    branches:  [ "main" ]
    paths:
      - "serene/**"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Replace dart-lang/setup-dart with Flutter setup
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'

      - name: Install dependencies
        working-directory: serene
        run: flutter pub get

      - name: Analyze project source
        working-directory: serene
        run: flutter analyze

      - name:  Run tests
        working-directory:  serene
        run: flutter test
