name: Flutter

on:
  push:
    branches: [ "main" ]
    paths:
      - "serene/**"
  pull_request:
    branches:  [ "main" ]
    paths:
      - "serene/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'

      # Install dependencies for the main Flutter app
      - name: Install Flutter dependencies
        working-directory: serene
        run: flutter pub get

      # Install dependencies for the backend
      - name: Install Backend dependencies
        working-directory: serene/backend
        run: dart pub get

      # Analyze the Flutter project
      - name: Analyze project source
        working-directory: serene
        run: flutter analyze

      # Run tests for the Flutter project
      - name: Run tests
        working-directory: serene
        run: flutter test
